"DaX functions used in this repository, The formulas are varied in the PBIX file according to tablename."
===============================================================================================================

#changed type
= Table.TransformColumnTypes(#"Promoted Headers",{{"customerID", type text}, {"gender", type text}, {"SeniorCitizen", Int64.Type}, {"Partner", type text}, {"Dependents", type text}, {"tenure", Int64.Type}, {"PhoneService", type text}, {"MultipleLines", type text},

= Table.AddColumn(#"Changed Type", "Risk category", each if [tenure] < 24 then "Risk 1" else if [tenure] < 48 then "Risk 2" else "Risk 3")
###############added conditional column

= Table.AddColumn(#"Added Conditional Column", "Loyalty", each if [tenure] < 12 then "< 1 year" else if [tenure] < 24 then "< 2 years" else if [tenure] < 36 then "< 3 years" else if [tenure] < 48 then "< 4 years" else if [tenure] < 60 then "< 5 years" else "< 6 years")

###############added conditional column

= Table.RemoveColumns(#"Added Conditional Column1",{"Risk category"}) 
##########removed columns

CHurn pivot groups'
= Table.AddColumn(#"Changed Type", "Risk category", each if [tenure] < 24 then "Risk 1" else if [tenure] < 48 then "Risk 2" else "Risk 3")
= Table.AddColumn(#"Added Conditional Column", "Loyalty", each if [tenure] < 6 then "< 6 months" else if [tenure] < 12 then "< 12 months" 
Table.AddColumn(#"Added Conditional Column", "Loyalty", each if [tenure] < 6 then "< 6 months" else if [tenure] < 12 then "< 12 months" else if [tenure] < 18 then "< 18 months" else if [tenure] < 24 then "< 2 years" else if [tenure] < 36 then "< 3 years" else if [tenure] < 48 then "< 4 years" else "4 years +")
---------------------------------------------------------------------------------------------------------------------------------
Measure :  churn rate%

churn rate % = DIVIDE (CALCULATE(COUNT(churn[Churn]), churn[Churn] = "yes" ),CALCULATE ( COUNT (churn[Churn]), ALLSELECTED (churn[Churn] ) )
)
===================================================
Count of Churn for Yes = 
CALCULATE(COUNTA('churn'[Churn]), 'churn'[Churn] IN { "Yes" })
========================================================
Count of DeviceProtection for Yes = 
CALCULATE(
	COUNTA('churn'[DeviceProtection]),
	'churn'[DeviceProtection] IN { "Yes" }
)
=========================================================
Count of MultipleLines for Yes = 
CALCULATE(
	COUNTA('churn'[MultipleLines]),
	'churn'[MultipleLines] IN { "Yes" }
)
==========================================================
Count of OnlineBackup for Yes = 
CALCULATE(
	COUNTA('churn'[OnlineBackup]),
	'churn'[OnlineBackup] IN { "Yes" }
)
=============================================================
Count of OnlineSecurity for Yes = 
CALCULATE(
	COUNTA('churn'[OnlineSecurity]),
	'churn'[OnlineSecurity] IN { "Yes" }
)
=============================================================
Count of PhoneService for Yes = 
CALCULATE(
	COUNTA('churn'[PhoneService]),
	'churn'[PhoneService] IN { "Yes" }
)
=================================================================
Count of StreamingMovies for Yes = 
CALCULATE(
	COUNTA('churn'[StreamingMovies]),
	'churn'[StreamingMovies] IN { "Yes" }
)
============================================================================
Count of StreamingTV for Yes = 
CALCULATE(COUNTA('churn'[StreamingTV]), 'churn'[StreamingTV] IN { "Yes" })
============================================================================
Count of TechSupport for Yes = 
CALCULATE(COUNTA('churn'[TechSupport]), 'churn'[TechSupport] IN { "Yes" })
==============================================================================
Dependents in % = DIVIDE(CALCULATE(COUNT(churn[Dependents]), churn[Dependents]="Yes", churn[Churn]= "Yes"), CALCULATE(COUNT(churn[Dependents]), churn[Churn]="Yes"),0)
========================================================================================================
Device protection in % = DIVIDE(CALCULATE(COUNT(churn[DeviceProtection]), churn[DeviceProtection]="Yes", churn[Churn]="Yes"),CALCULATE(COUNT(churn[DeviceProtection]),churn[Churn]="Yes"),0)
=========================================================================================================
Multiple lines no in % = DIVIDE(CALCULATE(COUNT(churn[MultipleLines]), churn[MultipleLines]="No", churn[Churn]="Yes"),CALCULATE(COUNT(churn[MultipleLines]),churn[Churn]="Yes", churn[MultipleLines] <> "No phone service"),0)
=============================================================================================================
Multiple Lines yes in % = DIVIDE(CALCULATE(COUNT(churn[MultipleLines]), churn[MultipleLines]="Yes", churn[Churn]= "Yes"), CALCULATE(COUNT(churn[MultipleLines]), churn[Churn]="Yes", churn[MultipleLines] <> "No phone service"),0)
=============================================================================================================
Online Bacup in % = DIVIDE(CALCULATE(COUNT(churn[OnlineBackup]), churn[OnlineBackup]="Yes", churn[Churn]="Yes"),CALCULATE(COUNT(churn[OnlineBackup]),churn[Churn]="Yes"),0)
=============================================================================================================
Online Sec. in % = DIVIDE(CALCULATE(COUNT(churn[OnlineSecurity]), churn[OnlineSecurity]="Yes", churn[Churn]="Yes"),CALCULATE(COUNT(churn[OnlineSecurity]),churn[Churn]="Yes"),0)
=============================================================================================================
Partner in % = DIVIDE(CALCULATE(COUNT(churn[Partner]), churn[Partner]="Yes", churn[Churn]= "Yes"), CALCULATE(COUNT(churn[Partner]), churn[Churn]="Yes"),0)
=================================================================================================================
Phone Service in % = DIVIDE(CALCULATE(COUNT(churn[PhoneService]), churn[PhoneService]="Yes", churn[Churn]="Yes"),CALCULATE(COUNT(churn[PhoneService]),churn[Churn]="Yes"),0)
======================================================================================================================
SeniorCitizen in % = DIVIDE(CALCULATE(COUNT(churn[SeniorCitizen]), churn[SeniorCitizen]=1, churn[Churn]= "Yes"), CALCULATE(COUNT(churn[SeniorCitizen]), churn[Churn]="Yes"),0)
=======================================================================================================================
Streaming Movies in % = DIVIDE(CALCULATE(COUNT(churn[StreamingMovies]), churn[StreamingMovies]="Yes", churn[Churn]="Yes"),CALCULATE(COUNT(churn[StreamingMovies]),churn[Churn]="Yes"),0)
==========================================================================================================================
Streaming TV in % = DIVIDE(CALCULATE(COUNT(churn[StreamingTV]), churn[StreamingTV]="Yes", churn[Churn]="Yes"),CALCULATE(COUNT(churn[StreamingTV]),churn[Churn]="Yes"),0)
==========================================================================================================================
Tech Support in % = DIVIDE(CALCULATE(COUNT(churn[TechSupport]), churn[TechSupport]="Yes", churn[Churn]="Yes"),CALCULATE(COUNT(churn[TechSupport]),churn[Churn]="Yes"),0)
=============================================================================================================================

>>> churn - unpivot groups








